Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role-table-access
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: MyPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:CreateObject
                Resource: "*"
